import Link from "next/link";
import { AdminShell } from "@/components/admin/admin-shell";
import { requireAdmin } from "@/lib/auth";
import { getPreflightQueue } from "@/lib/preflight/service";
import { cancelPreflightAction, retryPreflightAction } from "./actions";
const statuses = ["queued","running","retry_scheduled","failed","blocked","passed","skipped","cancelled"];
export default async function PreflightPage({ searchParams }: { searchParams: Promise<{status?: string; page?: string}> }) {
  const admin = await requireAdmin(); const params = await searchParams; let data: Awaited<ReturnType<typeof getPreflightQueue>> | null = null; try { data = await getPreflightQueue(params.status, Number(params.page)||1); } catch {}
  return <AdminShell email={admin.email}><header className="admin-heading"><div><p className="eyebrow">Phase 3</p><h1>Preflight queue</h1></div><Link className="button button-primary" href="/admin-portal/leads">Select leads</Link></header><section className="admin-card"><nav className="saved-views"><Link href="/admin-portal/preflight">All</Link>{statuses.map(s=><Link key={s} href={`/admin-portal/preflight?status=${s}`}>{s.replaceAll("_"," ")}</Link>)}</nav>{!data?<p className="muted">Connect the Phase 3 database migration to view jobs.</p>:data.items.length?<div className="table-wrap"><table><thead><tr><th>Business</th><th>Status</th><th>Attempts</th><th>Scheduled</th><th>Actions</th></tr></thead><tbody>{data.items.map(({job,businessName})=><tr key={job.id}><td><Link href={`/admin-portal/preflight/${job.id}`}><strong>{businessName}</strong></Link></td><td><span className="status-pill">{job.status.replaceAll("_"," ")}</span></td><td>{job.attemptCount}/{job.maxAttempts}</td><td>{job.scheduledAt.toLocaleString()}</td><td><div className="button-row">{["failed","blocked"].includes(job.status)&&<form action={retryPreflightAction}><input type="hidden" name="jobId" value={job.id}/><button className="button button-secondary">Retry</button></form>}{["queued","retry_scheduled"].includes(job.status)&&<form action={cancelPreflightAction}><input type="hidden" name="jobId" value={job.id}/><button className="button button-secondary">Cancel</button></form>}</div></td></tr>)}</tbody></table></div>:<div className="empty-state"><h2>No preflight jobs</h2><p>Select a bounded set of eligible leads from Leads to queue objective checks.</p></div>}</section></AdminShell>;
}
