import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { requireAdmin } from "@/lib/auth";
import { getAuditDetail } from "@/lib/audits/service";
import { addManualFindingAction, completeAuditReviewAction, reopenAuditReviewAction, reviewFindingAction } from "../actions";

export default async function AuditDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const admin = await requireAdmin(); const { id } = await params; const data = await getAuditDetail(id); if (!data) notFound();
  const categoryResults = (data.score?.categoryResults || {}) as Record<string, { maximum: number; awarded: number }>;
  return <AdminShell email={admin.email}>
    <header className="admin-heading"><div><p className="eyebrow">Objective deep audit</p><h1>{data.lead.businessName}</h1></div><span className="status-pill">{data.job.status.replaceAll("_", " ")}</span></header>
    <section className="admin-grid">
      <article className="admin-card"><h2>Imported business data</h2><dl className="detail-list"><div><dt>Website</dt><dd>{data.lead.websiteUrl || "Unavailable"}</dd></div><div><dt>Industry</dt><dd>{data.lead.industry || data.lead.category || "Unavailable"}</dd></div><div><dt>Location</dt><dd>{data.lead.location || [data.lead.city, data.lead.state].filter(Boolean).join(", ") || "Unavailable"}</dd></div></dl></article>
      <article className="admin-card"><h2>Phase 3 eligibility</h2><p><span className="status-pill">{data.decision.status.replaceAll("_", " ")}</span></p><p>{data.decision.explanation}</p></article>
      <article className="admin-card"><h2>Website Improvement Score</h2><p className="metric-value">{data.score ? `${data.score.totalScore} / 100` : "Unavailable"}</p><p>{data.score?.scoreBand.replaceAll("_", " ")}</p><p>Coverage: {data.score?.coveragePercent ?? 0}% · {data.score?.provisional ? "Provisional" : "Manually reviewed"}</p></article>
      <article className="admin-card"><h2>Audit Confidence</h2><p className="metric-value">{data.confidence?.level || "Unavailable"}</p><p>{data.confidence?.explanation}</p></article>
    </section>
    <section className="admin-card"><h2>Score breakdown</h2><ul className="check-list">{Object.entries(categoryResults).map(([category, result]) => <li key={category}><div><strong>{category.replaceAll("_", " ")}</strong></div><b>{result.awarded}/{result.maximum}</b></li>)}</ul></section>
    <section className="admin-card"><h2>Pages inspected or skipped</h2>{data.pages.length ? <ul className="admin-list">{data.pages.map((page) => <li key={page.id}><div><strong>{page.pageType}: {page.status}</strong><span>{page.finalUrl || page.requestedUrl}</span><span>{page.selectionReason}{page.statusReason ? ` · ${page.statusReason}` : ""}</span></div></li>)}</ul> : <p className="muted">No pages have been recorded.</p>}</section>
    <section className="admin-card"><h2>Evidence-backed findings</h2>{data.findings.length ? <ul className="admin-list">{data.findings.map((finding) => <li key={finding.id}><div><strong>{finding.category.replaceAll("_", " ")} · {finding.severity}</strong><span>{finding.administratorExplanation || finding.originalExplanation}</span><span>{finding.suggestedImprovement}</span><span>Source: {finding.source} · Confidence: {finding.confidence} · Review: {finding.verificationStatus}</span><details><summary>Objective evidence</summary><pre>{JSON.stringify(finding.evidence, null, 2)}</pre></details>{finding.verificationStatus === "pending" && <form action={reviewFindingAction} className="admin-form"><input type="hidden" name="findingId" value={finding.id}/><label>Decision<select name="status"><option value="verified">Verify</option><option value="rejected">Reject</option><option value="edited">Edit wording</option></select></label><label>Administrator explanation<textarea name="explanation" maxLength={1000}/></label><button className="button button-secondary">Record decision</button></form>}</div></li>)}</ul> : <p className="muted">No opportunity findings were created from available checks.</p>}</section>
    {data.latest && <section className="admin-card"><h2>Add a manual finding</h2><p className="muted">Label subjective observations clearly and include bounded evidence. Do not enter revenue-loss claims.</p><form action={addManualFindingAction} className="admin-form"><input type="hidden" name="runId" value={data.latest.id}/><label>Category<select name="category"><option value="manual_review_opportunity">Manual-review opportunity</option><option value="mobile_usability">Mobile usability</option><option value="conversion_path_cta">Conversion path and CTA</option><option value="performance">Performance</option><option value="technical_seo">Technical SEO</option><option value="accessibility">Accessibility</option><option value="reliability_security">Reliability and security</option></select></label><label>Severity<select name="severity"><option value="informational">Informational</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><label>Confidence<select name="confidence"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><label>Explanation<textarea name="explanation" required minLength={5} maxLength={1000}/></label><label>Evidence or reasoned observation<textarea name="evidence" required minLength={3} maxLength={1000}/></label><label>Suggested improvement<textarea name="suggestedImprovement" required minLength={5} maxLength={1000}/></label><label>Affected URL, if applicable<input name="affectedUrl" type="url"/></label><button className="button button-secondary">Add manual finding</button></form></section>}
    {data.latest && <section className="admin-card"><h2>Manual review and Phase 5 readiness</h2><p><strong>{data.latest.phaseFiveReady ? "Ready for Phase 5" : data.latest.reviewCompletedAt ? "Reviewed but not ready" : "Review incomplete"}</strong></p>{data.latest.reviewCompletedAt ? <form action={reopenAuditReviewAction} className="admin-form"><input type="hidden" name="runId" value={data.latest.id}/><label>Reason to reopen<textarea name="explanation" required minLength={5} maxLength={500}/></label><button className="button button-secondary">Reopen review</button></form> : <form action={completeAuditReviewAction}><input type="hidden" name="runId" value={data.latest.id}/><button className="button button-primary">Complete review and recalculate</button></form>}</section>}
    <section className="admin-grid"><article className="admin-card"><h2>Prior audit history</h2><ul className="admin-list">{data.runs.map((run) => <li key={run.id}><div><strong>{run.status.replaceAll("_", " ")}</strong><span>{run.createdAt.toLocaleString()} · {run.auditVersion}</span></div></li>)}</ul></article><article className="admin-card"><h2>Administrator activity</h2>{data.reviewEvents.length ? <ul className="admin-list">{data.reviewEvents.map((event) => <li key={event.id}><div><strong>{event.eventType.replaceAll("_", " ")}</strong><span>{event.explanation}</span><span>{event.administratorEmail} · {event.createdAt.toLocaleString()}</span></div></li>)}</ul> : <p className="muted">No review activity yet.</p>}</article></section>
  </AdminShell>;
}
